version: "3.4"

x-ariflow_common:
  &airflow-common
  build: .
  environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
#      AIRFLOW__WEBSERVER__WORKER_CLASS: gevent
      AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE: 'true'
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /app/src/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /app/src/plugins
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /app/src/logs
      AIRFLOW__CELERY__BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: 'false'
      AIRFLOW__CORE__LAZY_LOAD_PLUGINS: 'true'
      AIRFLOW__CORE__EXECUTE_TASKS_NEW_PYTHON_INTERPRETER: 'true'
      AIRFLOW__WEBSERVER__WORKERS: 5 # 2 * NUM_CPU_CORES + 1
      AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL: 18000 # Restart workers every 30min instead of 30seconds
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: 30000
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
  volumes:
    - ./src:/app/src
  depends_on:
    &airflow-common-depends-on
    rabbitmq:
      condition: service_healthy
    postgres:
      condition: service_healthy



services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    restart: always

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      retries: 3
    restart: always

  initdb:
    <<: *airflow-common
    command: bash -c "airflow db init  && airflow db upgrade && airflow db check-migrations && airflow users  create --role Admin --username ${AIRFLOW_USER} --email admin --firstname admin --lastname admin --password ${AIRFLOW_PASSWORD}"
    depends_on:
      <<: *airflow-common-depends-on

  scheduler:
    <<: *airflow-common
    command: airflow scheduler
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      initdb:
        condition: service_completed_successfully


  worker:
    <<: *airflow-common
    command: airflow celery worker
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      initdb:
        condition: service_completed_successfully

  airflow_webserver:
    <<: *airflow-common
    command: bash -c "airflow webserver --port 8080"
    ports:
      - 8080:8080
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 5s
      retries: 5
    depends_on:
      <<: *airflow-common-depends-on
      initdb:
        condition: service_completed_successfully



  airflow_flower:
    <<: *airflow-common
    command: airflow celery flower
    ports:
      - 5555:5555
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      initdb:
        condition: service_completed_successfully

  sql-server-db:
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_PASS}
      ACCEPT_EULA: "Y"
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    ports:
      - "1433:1433"
    volumes:
      - ./mssql_backups:/var/backups

volumes:
  pgdata:
